CREATE TABLE IF NOT EXISTS fact_match_stats (
    understat_match_id  INTEGER PRIMARY KEY,
    fpl_fixture_id      INTEGER,
    event               INTEGER,
    home_fpl_id     INTEGER,
    away_fpl_id     INTEGER,
    home_team_name  TEXT,
    away_team_name  TEXT,
    home_goals      INTEGER,
    away_goals      INTEGER,
    home_xg         REAL,
    away_xg         REAL,
    home_ppda       REAL,
    away_ppda       REAL,
    home_deep       INTEGER,
    away_deep       INTEGER,
    home_shots      INTEGER,
    away_shots      INTEGER,
    home_sot        INTEGER,
    away_sot        INTEGER,
    prob_home       REAL,
    prob_draw       REAL,
    prob_away       REAL,
    datetime        TEXT,
    UNIQUE(understat_match_id)
);
